### ISSUE TITLE
Can't use function return value in write context

### ISSUE THREAD

**Issue by AlwinEdwards** [jayarathina/Tamil-Bible-Database#6]
I got his error while using your api example.php. Can't use function return value in write context BibleLib\lib\medoo.php on line 531

Kindly help me to solve this error.

**Comment by jayarathina** [comment]
Can you please tell me the PHP and MySQL version you are using?

Also please post the full error so that I can know the origin of the error.

**Comment by AlwinEdwards** [comment]
Thank you for reply..

Versions:
PHP --> 5.4.31
MySQL --> 5.6.20

Full Error while using example.php in your api.
Fatal error: Can't use function return value in write context in BibleLib\lib\medoo.php on line 531

I think this is a type of null error. but i can't to solve. kindly help me for this. and Thank you for your valuable api and database

**Comment by jayarathina** [comment]
@AlwinEdwards , I have updated [Medoo library](http://medoo.in) to the latest version. Can you please check and confirm by downloading the latest version?

**Comment by AlwinEdwards** [comment]
Thank you for your support. Now it fixed the error
